import Head from "next/head";
import Image from "next/image";
import { Button, Col, Container, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import vector from "../../public/jumbo-img.png";
export default function Home() {
  return (
    <div>
      <Head>
        <title>AI Ghana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Container className={styles.hero_container}>
          <Row className="d-flex align-items-center justify-content-center">
            <Col md={6}>
              <div>
                <h1 className="text-capitalize">
                  Articificial intelligence ghana
                </h1>
                <p>
                  is a non-profit organization that promotes the use of
                  Artificial Intelligence in solving real problems in Ghana
                </p>
                <div className="flex gap-4">
                  <Button size="lg" className="btn-primary">
                    Join Us
                  </Button>
                </div>
              </div>
            </Col>
            <Col md={6} className="d-flex justify-content-center">
              <div>
                <Image
                  src={vector}
                  alt="Vector"
                  className="rounded-5"
                  width={500}
                  objectFit="contain"
                  height={500}
                />
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </div>
  );
}
