import Head from "next/head";
import Image from "next/image";
import { Button, Col, Container, Row } from "react-bootstrap";
import styles from "../styles/Home.module.scss";
import vector from "../../public/jumbo-img.png";
import Link from "next/link";
export default function Home() {
  return (
    <div>
      <Head>
        <title>AI Ghana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <Container className={styles.hero_container}>
          <Row className="d-flex align-items-center justify-content-center py-5">
            <Col md={6}>
              <div>
                <h1
                  className={`${styles.hero_text} text-capitalize`}
                  data-aos="fade-right"
                >
                  Articificial{" "}
                  <span className="text-primary">intelligence</span> ghana
                </h1>
                <p>
                  is a non-profit organization that promotes the use of
                  Artificial Intelligence in solving real problems in Ghana
                </p>
                <div className="flex gap-4" data-aos="zoom-out">
                  <Button
                    size="lg"
                    className="btn-primary"
                    style={{ borderRadius: 50 }}
                  >
                    Join Us
                  </Button>
                </div>
              </div>
            </Col>
            <Col md={6} className="d-flex justify-content-center">
              <div data-aos="fade-up" data-aos-delay={500}>
                <Image
                  src={vector}
                  alt="Vector"
                  className="rounded-5"
                  width={500}
                  objectFit="contain"
                  height={500}
                />
              </div>
            </Col>
          </Row>
        </Container>
      </section>
      <section>
        <Container>
          <Row className={styles.about}>
            <Col md={6} className="d-flex justify-content-center">
              <Image
                data-aos="flip-right"
                data-aos-delay={1300}
                src="/about.jpg"
                alt=""
                width={450}
                height={450}
                objectFit="cover"
              />
            </Col>
            <Col md={6}>
              <h2 data-aos="flip-left">
                About <span className="text-danger">AI Ghana</span>
              </h2>
              <p data-aos="fade-up-right">
                AI GHANA is a non-profit organization, run by the AI Ghana
                community, focused on promoting the use of Artificial
                Intelligence in solving real-world problems in Ghana, Africa and
                beyond.{" "}
              </p>
              <p data-aos="fade-down-right">
                Artificial Intelligence (AI) has become very essential in recent
                times, as it has become one of the main tools used for solving
                major problems we face daily. Ghanaians, and Africans for that
                matter, are faced with a lot of challenges that can be solved
                using AI. However, there is paucity of AI talents in our part of
                the world to take up these challenges.{" "}
              </p>
            </Col>
          </Row>
        </Container>
      </section>
      <section>
        <Container>
          <Row className="d-flex align-items-center">
            <Col md={6}>
              <div>
                <h2 data-aos="flip-left">
                  Our <span className="text-danger">Mission</span>
                </h2>
                <p data-aos="fade-up-right" data-aos-delay={1000}>
                  To provide technical AI skills to students and tech
                  enthusiasts to enable them in identifying and solving real
                  problems in their communities/organizations using the skills
                  acquired. In five to ten years, we aim to be the number one
                  go-to organization/community for AI talents.{" "}
                  <Link href="/">&rarr; Read more</Link>
                </p>
              </div>
            </Col>
            <Col md={6} className="d-flex justify-content-center">
              <Image
                data-aos="flip-right"
                src="/contact.jpg"
                alt=""
                width={450}
                height={450}
                objectFit="cover"
              />
            </Col>
          </Row>
        </Container>
      </section>
      <section className="vision">
        <Container>
          <Row className="d-flex align-items-center">
            <Col md={6} className="d-flex justify-content-center">
              <Image
                data-aos="flip-right"
                src="/mission.jpg"
                alt=""
                width={450}
                height={450}
                objectFit="cover"
              />
            </Col>
            <Col md={6}>
              <div>
                <h2 data-aos="flip-left">
                  Our <span className="text-danger">Vision</span>
                </h2>
                <p data-aos="fade-up-right">
                  To provide technical AI skills to students and tech To promote
                  the use of artificial intelligence in solving real-world
                  problems in Ghana, Africa and beyond.
                </p>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </div>
  );
}
